#!/usr/bin/env python3
"""Assemble the regional workflow report: planting dekad -> risk -> yield, 10 countries, 5 crops.

Every table is COMPUTED from the shipped products at build time and every figure is regenerated by
report/make_figures.py from those same products, so the report cannot drift from what the pipeline
actually produced. No figure is carried over from an earlier run.

    python report/make_figures.py && python report/build_report.py
"""
import os, re, subprocess, sys
import numpy as np, pandas as pd

H = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
R = os.path.join(H, "report")
sys.path.insert(0, H); sys.path.insert(0, f"{H}/crop_pipeline/irrigation")
from products import inventory
import irrigation_exposure as IRR
import ctm_mask as CTM
from crop_coverage import DROPPED, ACCEPTED, no_mask_band, no_calendar

# ---------------------------------------------------------------- equations (raw, never f-strings)
# pandoc converts TeX display math to OMML, so these become NATIVE WORD EQUATIONS in the .docx
# rather than the monospace code blocks a fenced block would produce.
EQ_BALANCE = r"""
$$WR_t = K_{c}(d)\cdot ET_{0,t}$$

$$W_{b,t} = SW_{t-1} + P_t$$

$$AET_t = \min\!\left(W_{b,t},\; WR_t\right)$$

$$SW_t = \min\!\left(\max\!\left(W_{b,t}-AET_t,\;0\right),\; WHC\right)$$

$$WRSI = 100\cdot\frac{\sum_{t} AET_t}{\sum_{t} WR_t}$$

where $t$ indexes dekads over the crop cycle, $d$ is dekads since planting, $K_c(d)$ is the FAO-56
crop coefficient at that stage, $ET_{0,t}$ is Hargreaves reference evapotranspiration, $P_t$ is
CHIRPS rainfall, and $WHC$ is water-holding capacity over the crop's own rooting depth. The supply
term $W_{b,t}=SW_{t-1}+P_t$ carries **no irrigation term** - see section 7.3.
"""

EQ_STRESS = r"""
$$S_{water} = \operatorname{clamp}\!\left(\sum_{s\,\in\,\{veg,\,flo,\,grf\}} K_{y,s}\left(1-\frac{AET_s}{WR_s}\right),\;0,\;1\right)$$

$$S_{heat} = \operatorname{clamp}\!\left(k_{H}\sum_{t\,\in\,flo}\max\!\left(0,\;T_{max,t}-T_{cap}\right),\;0,\;1\right)$$

$$S_{veg} = w_{v}\left(1-\mathrm{VCI}\right), \qquad w_{v}=0.4$$

$K_{y,s}$ is the FAO-33 stage yield-response factor, $k_H$ the heat coefficient per
heat-degree-dekad, $T_{cap}$ the crop's flowering heat threshold, and $w_v$ the vegetation
down-weight - $S_{veg}$ confirms the balance rather than driving it.
"""

EQ_CPI = r"""
$$CPI = 100\left(1-S_{water}\right)\left(1-S_{heat}\right)\left(1-S_{veg}\right)$$

$$Y_a = \frac{CPI}{100}\cdot Y_m$$

The combination is **multiplicative**, following FAO-33: a crop already lost to water deficit cannot
be further reduced proportionally by heat. $Y_m$ is the attainable ceiling, fitted by least squares
through the origin over HarvestStat units $i$ with reported yield $y_i$, weighted by crop area $w_i$:

$$\hat{Y}_m = \frac{\sum_i w_i\, y_i\, c_i}{\sum_i w_i\, c_i^{2}}, \qquad c_i = \frac{CPI_i}{100}$$
"""

EQ_CHAIN = r"""
$$S_{water}\;\longrightarrow\;CPI = 100\left(1-S_w\right)\left(1-S_h\right)\left(1-S_v\right)\;\longrightarrow\;Y_a = \frac{CPI}{100}\,Y_m$$
"""

FIG = "figs"          # relative, so the .md and the .docx both resolve
CROPS = ["maize", "sorghum", "wheat", "teff", "millet"]


def fig(name, caption):
    """One figure, ONE caption.

    Pandoc's implicit_figures turns `![alt](path)` into a figure whose caption IS the alt text, so
    emitting an italic line as well produced the caption twice in the .docx - once under the image
    as a real caption and once as body text."""
    return f"\n![{caption}]({FIG}/{name})\n"


def ym_skill():
    rows = []
    for m in re.finditer(r'#\s+(\w[\w ]+?)\s+(Long rains|Short rains|Meher|Season A|1st rains)\s+'
                         r'([\d.]+)\s+(\d{4}-\d{2}),\s*n(\d+)\s+([\d.]+) vs ([\d.]+)\s+r\s+(-?[\d.]+)',
                         open(f"{H}/src/cpi.py").read()):
        rows.append(dict(crop="maize", country=m.group(1).strip(), season=m.group(2),
                         ym=float(m.group(3)), n=int(m.group(5)), mae=float(m.group(6)),
                         mae_def=float(m.group(7)), r=float(m.group(8))))
    for crop, f in (("sorghum", "sorghum_pipeline/sorghum_params.py"),
                    ("wheat", "crop_pipeline/params/wheat.py"),
                    ("teff", "crop_pipeline/params/teff.py"),
                    ("millet", "crop_pipeline/params/millet.py")):
        blk = open(f"{H}/{f}").read().split("YM_CAL_CTM")[0]
        for m in re.finditer(r'\("([^"]+)",\s*"([^"]+)"\):\s*([\d.]+),?\s*#(.*)', blk):
            cm = m.group(4)
            rr = re.search(r'\br\s+(-?[\d.]+)', cm); nn = re.search(r'\bn(\d+)', cm)
            mm = re.search(r'MAE\s+([\d.]+)\s+vs\s+([\d.]+)', cm)
            rows.append(dict(crop=crop, country=m.group(1), season=m.group(2),
                             ym=float(m.group(3)), n=int(nn.group(1)) if nn else None,
                             mae=float(mm.group(1)) if mm else None,
                             mae_def=float(mm.group(2)) if mm else None,
                             r=float(rr.group(1)) if rr else None))
    return pd.DataFrame(rows)


def md_table(df, cols=None, floatfmt="{:.2f}"):
    d = df[cols] if cols else df
    head = "| " + " | ".join(str(c) for c in d.columns) + " |"
    sep = "|" + "---|" * len(d.columns)
    out = [head, sep]
    for r in d.itertuples(index=False):
        cells = []
        for v in r:
            if v is None or (isinstance(v, float) and np.isnan(v)):
                cells.append("—")
            elif isinstance(v, float):
                cells.append(floatfmt.format(v))
            else:
                cells.append(str(v))
        out.append("| " + " | ".join(cells) + " |")
    return "\n".join(out)


def main():
    inv = inventory()
    n_prod = len(inv)
    by_crop = pd.Series([p["crop"] for p in inv]).value_counts()
    countries = sorted({p["country"] for p in inv})
    sk = ym_skill()
    exp = pd.read_csv(f"{H}/crop_pipeline/irrigation/product_irrigation_exposure.csv")
    grades = exp.exposure.value_counts()

    # ---------- per-product master table
    master = []
    for p in inv:
        d = pd.read_csv(p["csv"])
        row = dict(crop=p["crop"], country=p["country"].replace("_", " "), season=p["season"],
                   units=len(d))
        w = d.get("n_px", pd.Series(1, index=d.index)).fillna(0) * \
            d.get("crop_area_frac", pd.Series(1, index=d.index)).fillna(0)
        if w.sum() <= 0:
            w = pd.Series(1.0, index=d.index)
        for c, lab in (("modal_dekad", "plant_dk"), ("cpi", "CPI"), ("yield_tha", "t/ha"),
                       ("fail_pct", "fail%"), ("mean_deficit_mm", "def_mm"), ("fcci", "FCCI")):
            row[lab] = (round(float(np.average(d[c].fillna(0), weights=w)), 1)
                        if c in d.columns and d[c].notna().any() else None)
        g = IRR.grade(p["country"], p["crop"])
        row["irrigation"] = "—" if g == "negligible" else g
        s = sk[(sk.crop == p["crop"]) & (sk.country == p["country"].replace("_", " "))]
        row["Ym"] = float(s.ym.iloc[0]) if len(s) else None
        row["r"] = float(s.r.iloc[0]) if len(s) and s.r.notna().any() else None
        master.append(row)
    M = pd.DataFrame(master).sort_values(["crop", "country", "season"])
    M.to_csv(f"{R}/product_master_table.csv", index=False)

    anti = int((sk.r < 0).sum()); usable = int((sk.r >= 0.4).sum())
    dmp_a = pd.read_csv(f"{H}/maize_ctm/dmp_rank_test_anti.csv") \
        if os.path.exists(f"{H}/maize_ctm/dmp_rank_test_anti.csv") \
        else pd.read_csv(f"{H}/maize_ctm/dmp_rank_test.csv")
    dmp_c = pd.read_csv(f"{H}/maize_ctm/dmp_rank_test_control.csv")
    mask = pd.read_csv(f"{H}/maize_ctm/mask_comparison.csv").dropna(subset=["rho_rank"])

    doc = f"""---
title: "Crop Condition Monitoring and Forecasting for the ICPAC Region"
subtitle: "From planting dekad to risk maps to yield estimates — as-built methodology, {n_prod} products across {len(countries)} countries and {len(CROPS)} crops"
date: "26 September 2026"
---

# 1. Scope and what this report is

This is an **as-built** description of the operational pipeline: what it computes, from which data,
with which parameters, and how well each output has been shown to work. It covers the whole chain —
**planting dekad → risk maps → yield estimates** — for **{n_prod} products**:
{", ".join(f"{v} {k}" for k, v in by_crop.items())}, across **{len(countries)} countries**
({", ".join(c.replace("_", " ") for c in countries)}).

Where the as-built method departs from the Inception Report, §8 states the departure, the reason,
and the peer-reviewed basis for it.

**Every table here is computed from the shipped products at build time, and every figure is
regenerated from those same products by `report/make_figures.py`.** No figure is carried over from
an earlier run. Rebuild with:

```bash
python report/make_figures.py && python report/build_report.py
```

## 1.1 Headline state of the pipeline

| | |
|---|---|
| products built | **{n_prod}** ({", ".join(f"{v} {k}" for k, v in by_crop.items())}) |
| countries | {len(countries)} |
| yield ceilings fitted against official statistics | **{len(sk)}** of {n_prod} |
| …of which rank admin units **usably** (r ≥ 0.4) | **{usable}** |
| …of which rank admin units **backwards** (r < 0) | **{anti}** |
| products where a rainfed balance misreads irrigation | **{int(n_prod - grades.get('negligible', 0))}** ({int(grades.get('INVALID as rainfed', 0))} invalid, {int(grades.get('materially biased', 0))} materially biased, {int(grades.get('locally biased', 0))} locally biased) |
| tier-2 metrics (SPI-3, deficit, LVPD, FCCI) | complete for sorghum, wheat, teff, millet |

**The honest summary is that planting dekad is the strongest link in the chain, risk is sound where
the crop is rainfed, and yield is the weakest — {anti} of {len(sk)} fitted ceilings order admin units
backwards.** §7 and §9 give the evidence and what to do about it.

# 2. Countries, crops and coverage

The **ICPAC crop-type mask decides which crops run in which country**. A season-calendar row for a
country whose mask carries no band for that crop cannot be computed, and is dropped at planning time
rather than failing mid-build (`crop_coverage.py`).

{fig("chart_coverage.png", "Figure 1. What the crop-type mask permits and what was built. 'mask only' = buildable, no calendar row yet; 'dropped' = a decision, recorded with its evidence.")}

**Deliberate exclusions**, recorded in `crop_coverage.ACCEPTED` / `.DROPPED` so a decision is never
mistaken for an oversight:

- **Sudan maize, Eritrea maize** — no mask band. Maize is not a crop of consequence in either and is
  intentionally neither mapped nor run. The calendar rows are legacy placeholders.
- **South Sudan maize — dropped.** {DROPPED[("maize", "South_Sudan")][:300]}…
- **Rwanda wheat (0.019 Mha), Burundi wheat (0.003 Mha)** — buildable, deferred on area.

# 3. Data inputs

| input | product | role | reference |
|---|---|---|---|
| Rainfall | CHIRPS v2.0, daily/dekadal, 0.05° | onset rule, water balance supply term, SPI-3 | Funk et al. 2015 |
| Temperature | ERA5-Land hourly → dekadal Tmin/Tmax | Hargreaves ET₀, flowering heat | Muñoz-Sabater et al. 2021 |
| Reference ET | Hargreaves–Samani from ERA5-Land | crop water requirement `Kc·ET₀` | Hargreaves & Samani 1985 |
| Soil water | SoilGrids 2.0 texture → Saxton–Rawls θ₃₃/θ₁₅₀₀ | WHC over the crop's rooting depth | Poggio et al. 2021; Saxton & Rawls 2006 |
| Optical | Sentinel-2 L2A, NDRE | green-up onset cue | Eisfelder et al. 2024 |
| Radar | Sentinel-1 GRD, VH/VV → RVI | cloud-proof onset cue | (SAR SOS literature, §11) |
| Canopy | MODIS MCD15A3H FPAR | onset cue, zFPAR anomaly | Myneni et al. |
| Biomass | MODIS MOD17A2HGF GPP → DMP | independent yield-ranking covariate | Running et al. 2004; Monteith 1972 |
| Crop area | ICPAC crop-type mask, 100 m (MapSPAM prior) | the stratum every product is computed over | IFPRI MapSPAM; §4 |
| Irrigation | MapSPAM 2020 `_I`/`_A` physical area | exposure grading (§7.3) | IFPRI MapSPAM |
| Boundaries | GADM 4.1 (GAUL where absent) | zonal reduction | GADM |
| Yield statistics | HarvestStat Africa v1.2 | Ym calibration and validation | Lee et al. 2025 |

# 4. The crop-type mask — the stratum everything is computed over

Every product is computed **inside a crop-specific mask**, not over all cropland. The ICPAC
crop-type mask is a dasymetric allocation of MapSPAM crop shares onto a four-lineage,
sixteen-source-year stable cropland vote, reweighted by agro-climatic suitability and satellite crop
evidence, and calibrated to sub-national statistics where they exist. It reproduces reported crop
area to **92–99 %** across the eight maize countries.

This **is** the Inception Report's Tier 1, built stronger than the report assumed (§8.1).

`ctm_mask.crop_mask()` **raises rather than falling back**. That matters: the generic
`run.crop_mask_image` would return the WorldCereal *temporary-crops* extent — all cropland — for any
non-maize crop. No shipped product ever ran that way, because sorghum, wheat, teff and millet used
the crop-type mask from the start; the raise is what keeps it that way.

# 5. Module 1 — Planting dekad (onset)

## 5.1 Three onset routes, chosen per product

1. **Green-up cue fusion** — Sentinel-2 NDRE + MODIS FPAR + Sentinel-1 RVI, for main seasons where
   cloud allows. Fusing an optical cue with SAR is what makes onset retrievable under cloud
   (Eisfelder et al. 2024; SAR-SOS literature).
2. **Rainfall-anchored onset** — the FEWS/GeoWRSI rule: 25 mm in a dekad followed by 20 mm in each of
   the next two, with a **5+7 dekad false-start gate** (Senay & Verdin 2003; Sivakumar 1988;
   Stern et al. 1982). Used for short and second seasons, and for cloudy equatorial highlands.
3. **Fixed scheme date** — for irrigated products, where planting is scheduled rather than
   rain-driven and neither detector can fire (§7.3).

{fig("chart_planting_windows.png", "Figure 2. Detected planting window per product — median p10 to p90 across admin units, dot = p50. The spread is the product's own detected variability, not the calendar window.")}

{fig("map_planting_maize.png", "Figure 3. Maize — modal planting dekad, 2024. One hue, dark to bright: dekad is an ordered quantity and a qualitative palette would invite the reader to see categories where there is a sequence.")}

{fig("map_planting_sorghum.png", "Figure 4. Sorghum — modal planting dekad, 2024, 18 products across 10 countries.")}

{fig("map_planting_wheat.png", "Figure 5. Wheat — modal planting dekad, 2024.")}

{fig("map_planting_millet.png", "Figure 6. Millet — modal planting dekad, 2024.")}

{fig("map_planting_teff.png", "Figure 7. Teff — modal planting dekad, Ethiopia Meher 2024.")}

## 5.2 Validation — the strongest link in the chain

Against **4.8 million Kenyan farmer planting records** (MAM 2024): **92.9 % of admin units within
±2 dekads**, and **100 % within the GIEWS calendar window**. Ethiopia Meher: **100 % in window**.

This is the only part of the chain with independent ground truth at scale, and it is the part that
performs best. Outside Kenya and Ethiopia there is no comparable reference, so planting dekad
elsewhere is validated only against calendar plausibility.

# 6. Module 2 — Risk monitoring

## 6.1 The water balance

A single-layer FAO-56 dekadal bucket (Allen et al. 1998), stepped over each pixel's own cycle:

{EQ_BALANCE}

with a dry start (`init_soil_water_frac = 0.0`), the WRSI convention (Verdin & Klaver 2002;
Senay & Verdin 2003).

## 6.2 Stress components

{EQ_STRESS}

Ky is the FAO-33 stage yield-response factor (Doorenbos & Kassam 1979) and is **the most
consequential parameter set in the pipeline** — maize's flowering Ky of 1.50 against sorghum's 0.55
means a flowering deficit costs maize roughly three times what it costs sorghum.

{fig("chart_stress_decomposition.png", "Figure 8. What actually drives CPI in each product. Water stress dominates almost everywhere — which is exactly why unmodelled irrigation (§7.3) is the pipeline's largest systematic error.")}

{fig("map_wrsiflo_sorghum.png", "Figure 9. Sorghum — WRSI at flowering, the critical stage.")}

{fig("map_risk_maize.png", "Figure 10. Maize — crop-failure risk, ASAP convention: % of crop area with stage WRSI < 50 (Rembold et al. 2019).")}

{fig("map_risk_sorghum.png", "Figure 11. Sorghum — crop-failure risk, 2024.")}

{fig("map_deficit_sorghum.png", "Figure 12. Sorghum — cumulative season water deficit (mm). On an irrigated product this quantity is the irrigation requirement, not crop stress (§7.3).")}

{fig("map_spi_sorghum.png", "Figure 13. Sorghum — SPI-3 at end of season, the meteorological drought context for the balance.")}

{fig("map_fcci_sorghum.png", "Figure 14. Sorghum — fused canopy condition (FCCI) from Sentinel-2, Sentinel-1 and FPAR: an observation-side check on a model-side product.")}

{fig("map_viable_sorghum.png", "Figure 15. Sorghum — share of crop area planted before the climatological last viable planting date (LVPD).")}

# 7. Module 3 — Crop Performance Index and yield

## 7.1 The model

{EQ_CPI}

Ym is fitted by least squares through the origin of reported yield on CPI, with admin units weighted
by crop area, against HarvestStat Africa v1.2 (Lee et al. 2025), 70/30 split repeated 200 times. The
ceiling is the *attainable* yield in the yield-gap sense (van Ittersum et al. 2013; Lobell et al. 2009).

{fig("map_cpi_sorghum.png", "Figure 16. Sorghum — Crop Performance Index, 2024.")}

{fig("map_yield_sorghum.png", "Figure 17. Sorghum — estimated yield (t/ha), 2024.")}

{fig("map_cpi_maize.png", "Figure 18. Maize — Crop Performance Index, 2024.")}

{fig("map_yield_maize.png", "Figure 19. Maize — estimated yield (t/ha), 2024.")}

## 7.2 Yield is the weakest link, and here is the evidence

{fig("chart_ym_skill.png", "Figure 20. Yield-pattern skill of every fitted ceiling. Bars left of zero are products where the model orders admin units BACKWARDS against reported yield.")}

Of **{len(sk)} fitted ceilings**: **{usable} rank usably** (r ≥ 0.4), **{anti} rank backwards** (r < 0).

A ceiling with r < 0 sets a plausible national average and then puts the wrong districts at the
bottom. In an early-warning product that is worse than no ranking, because it carries the authority
of a number. **These products should be read as levels, not as rankings**, until the cause is fixed.

{md_table(sk.sort_values("r")[["crop", "country", "season", "ym", "n", "r"]].head(10),
          floatfmt="{:.2f}")}

## 7.3 Irrigation — the largest known systematic error

The balance is **rainfed by construction**: `Wb = SW + P` credits soil water and rainfall and
nothing else. Where a crop is irrigated, the scheme meets a shortfall the model never sees, so
WRSI and `S_water` measure the **irrigation requirement** while being reported as crop stress, and
CPI and yield come out low.

Exposure is graded per (country, crop) from MapSPAM 2020's irrigated/rainfed technology split:
**{int(grades.get('INVALID as rainfed', 0))} invalid as a rainfed product,
{int(grades.get('materially biased', 0))} materially biased, {int(grades.get('locally biased', 0))} locally biased,
{int(grades.get('negligible', 0))} unaffected.**

{fig("chart_irrigation.png", "Figure 21. Admin units where the rainfed balance is reading irrigation demand as crop stress.")}

The clearest measurable case is **Sudan millet Kharif**: across its 15 states CPI ranks *negatively*
against the irrigated share (Spearman ρ = −0.678, p = 0.005) — Al Jazirah (71.9 % irrigated) and
Khartoum (95.4 %) score below fully-rainfed Darfur.

**Exposure is not proof of corruption.** Sudan sorghum has the most irrigated area of any product
(288,569 ha) yet ρ = −0.17 (p = 0.50), because the 3.3 Mha Al Qadarif bulk is rainfed. The grade
flags a product for inspection; the correlation decides.

Every Earth Engine asset carries `irrigation_exposure`; the apps show a banner; Sudan wheat Shitwi
is excluded from apps and Atlas, its asset retained because the deficit *is* the irrigation
requirement. Full treatment: `crop_pipeline/docs/IRRIGATED_WATER_BALANCE.md`.

## 7.4 DMP as a rescue for the products where the balance fails

Dry-matter productivity (MOD17 GPP → DMP; Monteith 1972; Running et al. 2004) was tested as an
independent **ranking covariate** — not as a replacement for CPI, and not as a level product, since
DMP cannot see ASAL crop failure (implied harvest index 0.02, far outside the 0.30–0.55 agronomic
range of Hay 1995).

The test is **rank-only**, which removes DMP's dominant uncertainty: Spearman ρ is invariant to
monotonic transforms, so harvest index, above-ground fraction and grain moisture cannot affect it.

{fig("chart_dmp_rank.png", "Figure 22. DMP vs CPI as a ranking covariate, paired bootstrap 95 % CI (Efron & Tibshirani 1993). Left panel: products where CPI ranks backwards. Right panel: the control set where CPI already works.")}

| set | DMP better | CPI better | indistinguishable | median Δρ |
|---|---|---|---|---|
| CPI ranks **backwards** (n={len(dmp_a)}) | **{int((dmp_a.verdict=='DMP better').sum())}** | {int((dmp_a.verdict=='CPI better').sum())} | {int((dmp_a.verdict=='no difference').sum())} | **{dmp_a.d_rho.median():+.3f}** |
| CPI **already works** (n={len(dmp_c)}) | {int((dmp_c.verdict=='DMP better').sum())} | {int((dmp_c.verdict=='CPI better').sum())} | {int((dmp_c.verdict=='no difference').sum())} | {dmp_c.d_rho.median():+.3f} |

DMP's ρ is positive in 6 of 8 anti-correlated products; CPI's is positive in **0 of 8**. On the
control set the two are a dead heat. The supported claim is therefore the narrow one:
**DMP adds nothing where the water balance already works, and recovers a usable ranking where it
does not.**

**It is now shipped on exactly those 8 products** as a `dmp` column at both admin levels and as a
layer in the risk monitor, and is absent everywhere else. A blend was tested before recommending
anything — the mean of the two percentile ranks — and **it loses**: DMP alone is the best index on
6 of the 8, CPI on 1 (Kenya short-rains sorghum, where both are negative) and the blend on 1
(Burundi Season A, n = 7, where the two tie at −0.071). Averaging a good ranking with an inverted
one drags it back toward zero, which is what the numbers show. **Use DMP for ranking on these
products, not for level** — it cannot see ASAP crop failure (implied harvest index 0.02, far outside
the 0.30–0.55 agronomic range of Hay 1995).

# 8. Departures from the Inception Report, and why

Each departure states what the report proposed, what was built, and the peer-reviewed basis.

## 8.1 Crop typing: Tier 1 was built stronger than proposed, Tier 3 was not attempted

*Report:* a three-tier strategy — Tier 1 a MapSPAM area-fraction prior over a cropland mask; Tier 2
label acquisition; Tier 3 a retrained S1/S2 phenometric classifier, adopted only if it beat Tier 1
on zone-level anomaly skill against FEWS NET IPC.

*Built:* Tier 1, but as a four-lineage sixteen-source-year cropland vote with suitability
reweighting, satellite crop evidence and calibration to sub-national statistics — reproducing
reported area to 92–99 %. **Tier 2 produced no usable labels, so Tier 3 is correctly not attempted**:
the report's own gate makes Tier 3 conditional on Tier 2.

*Basis:* Van Tricht et al. 2023 (WorldCereal) confirms no global millet or teff class exists, which
is why a SPAM-prior mask is the only route to those crops; Eisfelder et al. 2024 is the S1+S2
classifier the report's Tier 3 would have been, and needs labels the region does not have.

## 8.2 WRSI computed inside Earth Engine, not GeoWRSI

*Report:* the FEWS GeoWRSI convention. *Built:* the same algorithm (Verdin & Klaver 2002;
Senay & Verdin 2003) reimplemented as a dekadal bucket in Earth Engine.

*Justification:* GeoWRSI is a desktop tool over pre-gridded inputs; running the identical recursion
in Earth Engine lets the balance use **per-pixel planting dates** and **per-pixel rooting-depth WHC**
from SoilGrids (Poggio et al. 2021; Saxton & Rawls 2006) at 250 m, which the desktop route cannot.
The algorithm is unchanged; only where it runs, and at what resolution, has changed.

## 8.3 Cue-fusion green-up onset alongside the rainfall rule

*Report:* rainfall-threshold onset. *Built:* both, chosen per product.

*Justification:* the rainfall rule cannot fire where a season is not rain-triggered — Sudan's
November-sown irrigated wheat produced **zero valid pixels** on the 25/20 mm rule. Conversely,
green-up fusion fails under persistent equatorial-highland cloud: Rwanda and Burundi Season A
returned ~64 planting pixels against 3,365 crop pixels until they were routed to the rainfall rule.
Neither detector is sufficient alone, and the failure modes are complementary — the optical/SAR
fusion literature (Eisfelder et al. 2024) is explicit that SAR is the cloud-proof cue.

## 8.4 Multiplicative CPI rather than an additive index

*Justification:* FAO-33 (Doorenbos & Kassam 1979) combines stage water-deficit effects
multiplicatively, and the same logic applies across stress types: a crop that has already failed for
water cannot be further damaged proportionally by heat. An additive index would let a good heat score
compensate a fatal water deficit.

## 8.5 `S_veg` is a down-weighted confirmation, not a driver

*Justification:* tested and rejected as a driver. DMP as `S_veg` gave no rank gain in any season
(Ethiopia admin-2, n = 39, ρ ≈ 0 for both arms). Vegetation indices are diagnostic mid-season
(Funk & Budde 2009; Rembold et al. 2013) and confirm what the balance already implies rather than
adding independent information.

## 8.6 Ethiopia Meher maize keeps the operative calendar window

*Justification:* decided by A/B test, not assertion. The operative window beats GEOGLAM CM4EW by
Δρ **+0.355 [+0.163, +0.564]** and the Inception Report window by **+0.463 [+0.229, +0.710]**
(paired bootstrap, Efron & Tibshirani 1993) — the first A/B in the project whose intervals exclude
zero. Coverage declines monotonically with the alternatives.

## 8.7 Sorghum calendars follow Inception Report Table 2.0

Not a departure but a deliberate alignment, recorded because GEOGLAM CM4EW ships a
sorghum-*specific* calendar that disagrees with the report for 6 of the 9 products it covers, by up
to 3 dekads. The CM4EW values are retained in parallel `cm4ew_*` columns for partner validation.

## 8.8 Irrigation is flagged, not corrected

*Departure:* the report assumes a rainfed balance throughout. *Built:* the same rainfed balance, plus
an explicit per-product exposure grade (§7.3), because pretending the issue does not exist would
misreport the Gezira as a crop failure.

## 8.9 Crop-type mask replaces WorldCereal as the stratum — for every crop except maize

*Status:* sorghum, wheat, teff and millet run on the crop-type mask. Maize still ships on WorldCereal.
All 16 maize products were re-run on the crop-type mask and compared.

{fig("chart_mask_comparison.png", "Figure 23. WorldCereal vs ICPAC crop-type mask for maize — same balance, same parameters, same Ym. Only the stratum differs.")}

Over {len(mask)} comparable products the level barely moves (mean CPI **{mask.delta_mean.mean():+.2f}**)
and the ranking mostly holds (median ρ **{mask.rho_rank.median():.3f}**), but **{int((mask.rho_rank<0.8).sum())} products re-rank**
(Uganda 1st rains ρ 0.758, Burundi Season A ρ 0.734). Re-fitting Ym on the new footprint moves the
ceilings by a median **−6.7 %** yet does **not** improve skill: held-out MAE improves in only 2 of 7
and r falls in 5 of 7.

**Conclusion: do not switch wholesale.** The mask is better at what it was built for — area — but
that has not translated into better condition or yield. Switch per product, on evidence.

# 9. Known limitations

1. **Yield ranks backwards in {anti} of {len(sk)} fitted products** (§7.2). Read those as levels.
2. **{int(n_prod - len(sk))} of {n_prod} products have no fitted ceiling at all** — no sub-national statistics exist to fit against.
3. **Irrigation is unmodelled** (§7.3); {int(n_prod - grades.get('negligible', 0))} products carry exposure.
4. **Teff and millet parameters are first-pass analogues** — FAO-33 tabulates neither crop, so their flowering Ky is borrowed. A wrong Ky biases CPI in a way calibration cannot detect, because Ym absorbs the level and leaves the pattern wrong.
5. **MapSPAM 2020 is a 2020 snapshot.** Ethiopia's irrigated-wheat expansion post-dates it (exposure understated); Sudan's schemes have been disrupted since 2023 (possibly overstated).
6. **Total production is an upper bound** where a mask cannot distinguish season.
7. **Kenya short-rains season attribution** — ~39 % of mapped western short-rains area may be the standing long-rains crop. Both CPI and DMP fail there, which points at the mask and the season rather than at either predictor.
8. **DMP is a stand-in.** MOD17 GPP substitutes for Copernicus 300 m DMP, which is not in the Earth Engine catalogue.

# 10. Recommendations, in order of value

1. **Split the crop masks by technology** using MapSPAM `_I`/`_R`, and run irrigated and rainfed products separately. This is the single highest-value fix: it makes {int(n_prod - grades.get('negligible', 0))} exposed products interpretable and unblocks an honest Ym re-fit.
2. **Add DMP as a ranking covariate** on the {anti} anti-correlated products (§7.4) — evidence supports it there and nowhere else.
3. **Re-fit Ym on rainfed area only** once the split exists. Sudan sorghum's r = −0.33 is the test: it should turn positive.
4. **Resolve Kenya short-rains season attribution** before that product is used for targeting.
5. **Obtain a teff Ky** from Ethiopian trial data; sensitivity-test Ky_flo over 0.4–0.8 meanwhile.
6. **Refresh the irrigation layer** against a post-2020 source.
7. **Switch maize to the crop-type mask per product, not wholesale**, re-fitting Ym each time.

# 11. References

All references below are reproduced from the project's maintained bibliography,
`REFERENCES.md`, which carries the full annotated list.

**Reader's caveat, carried over from that file:** several DOIs are foundational standards cited from
established literature, and the 2023–2026 fusion papers were surfaced through web search during
development. **Verify every DOI against your own library before formal publication or submission.**
The MapSPAM release identifier in particular should be cited from the exact Dataverse record used.

"""
    refs = open(f"{H}/REFERENCES.md").read()
    refs = refs.split("\n", 1)[1]
    doc += refs
    doc += f"""

---

*Generated {pd.Timestamp('2026-09-26').date()} by `report/build_report.py` from {n_prod} shipped
products. Companion files: `report/product_master_table.csv` (every product, every headline metric),
`crop_products/<crop>/METHODOLOGY.md` (per-crop dossiers),
`crop_pipeline/docs/IRRIGATED_WATER_BALANCE.md`, `CPI_METHODOLOGY.md`, `ALL_COUNTRIES_2024.md`.*

# Appendix A — every product, every headline metric

Area-weighted means across admin-1 units. `r` is the yield-pattern skill of that product's fitted
ceiling; blank means no ceiling could be fitted.

{md_table(M, floatfmt="{:.2f}")}
"""
    p = os.path.join(R, "ICPAC_WORKFLOW_REPORT.md")
    open(p, "w").write(doc)
    print(f"wrote {p}  ({len(doc)/1000:.1f} k chars, {doc.count('!['):d} figures)")
    for ext, args in ((".docx", []), (".html", ["-s", "--toc", "--embed-resources"])):
        try:
            subprocess.run(["pandoc", "ICPAC_WORKFLOW_REPORT.md", "--resource-path", ".",
                            *args, "-o", "ICPAC_WORKFLOW_REPORT" + ext],
                           cwd=R, check=True, capture_output=True)
            print(f"  wrote ICPAC_WORKFLOW_REPORT{ext}")
        except subprocess.CalledProcessError as e:
            print(f"  [warn] {ext}: {e.stderr.decode()[:200]}")


if __name__ == "__main__":
    main()
