#!/usr/bin/env python3
"""Irrigation exposure of every (country, crop) in the pipeline — ONE source of truth.

The FAO-56 water balance in `src/wrsi_waterbalance.py` supplies its bucket from `Wb = SW + P`:
soil water plus CHIRPS rainfall, with a dry start (`init_soil_water_frac: 0.0`). There is no
irrigation term. So wherever a crop is irrigated, WRSI and S_water measure the IRRIGATION
REQUIREMENT while being reported as crop water stress, and CPI and yield come out low.

This module grades that exposure so the Earth Engine assets, the apps and the Atlas all say the
same thing. Imported by `run_all_crop.py`, `run_all_sorghum.py`, `app_data.py` and
`tag_assets_irrigation.py`.

Table generated by `crop_pipeline/irrigation/product_exposure.py` from SPAM 2020 V2r2 physical-area
rasters (`_I` irrigated vs `_A` all technologies) summed inside GADM 4.1 ADM_0 and ADM_1.
Regenerate with the four scripts in `crop_pipeline/irrigation/` — do not hand-edit the table.

Grades (area-weighted: a unit counts as compromised only at >=30 % irrigated AND >=1000 ha):
  INVALID as rainfed  national >= 40 %             do NOT report CPI, yield or stress at all
  materially biased   >=10 % national, or >=2 compromised units, or >=50,000 ha irrigated
  locally biased      >=1 compromised unit          national aggregates sound, named units are not
  negligible          none of the above             report as rainfed, no caveat

CAVEAT ON THE SOURCE: SPAM 2020 is a 2020 snapshot. Ethiopia's irrigated-wheat expansion came
after it (exposure understated) and Sudan's schemes have been disrupted since 2023 (possibly
overstated). These are as-of-2020 priors, not 2024 measurements.
"""

# (country, crop) -> (national_irr_pct, irr_area_ha, admin1_max_pct, grade, compromised_units)
EXPOSURE = {
    ("Sudan", "wheat"): (98.4, 290316, 100.0, "INVALID as rainfed", "Al Jazirah 99.7%; Kassala 100%; White Nile 100%; Khartoum 100%; Sennar 95.3%; Al Qadarif 99.7%; River Nile 100%"),
    ("Somalia", "maize"): (24.8, 23040, 46.2, "materially biased", "Shabeellaha Dhexe 46.2%; Jubbada Hoose 33.6%"),
    ("Somalia", "sorghum"): (12.0, 22408, 84.2, "materially biased", "Shabeellaha Dhexe 76.5%; Jubbada Hoose 84.2%"),
    ("Sudan", "sorghum"): (4.4, 288569, 50.6, "materially biased", "Al Jazirah 31%; Sennar 46.3%; White Nile 40.1%; Kassala 50.6%"),
    ("Sudan", "millet"): (0.4, 12081, 95.4, "materially biased", "Al Jazirah 71.9%; Kassala 41.1%"),
    ("Ethiopia", "maize"): (2.1, 29162, 96.8, "locally biased", "Afar 96.8%"),
    ("South_Sudan", "sorghum"): (4.4, 29682, 13.7, "negligible", None),
    ("Tanzania", "maize"): (1.3, 41772, 2.9, "negligible", None),
    ("Ethiopia", "sorghum"): (1.1, 19051, 4.6, "negligible", None),
    ("South_Sudan", "maize"): (0.5, 887, 2.1, "negligible", None),
    ("Ethiopia", "teff"): (0.4, 9321, 3.2, "negligible", None),
    ("Ethiopia", "wheat"): (0.4, 7745, 3.5, "negligible", None),
    ("Kenya", "maize"): (0.3, 5818, 14.5, "negligible", None),
    ("Kenya", "sorghum"): (0.2, 339, 3.7, "negligible", None),
    ("Uganda", "maize"): (0.2, 1080, 19.3, "negligible", None),
    ("Burundi", "maize"): (0.0, 0, 0.0, "negligible", None),
    ("Burundi", "sorghum"): (0.0, 0, 0.0, "negligible", None),
    ("Eritrea", "millet"): (0.0, 0, 0.0, "negligible", None),
    ("Eritrea", "sorghum"): (0.0, 0, 0.0, "negligible", None),
    ("Kenya", "wheat"): (0.0, 0, 0.0, "negligible", None),
    ("Rwanda", "maize"): (0.0, 0, 0.0, "negligible", None),
    ("Rwanda", "sorghum"): (0.0, 0, 0.0, "negligible", None),
    ("Tanzania", "sorghum"): (0.0, 0, 0.0, "negligible", None),
    ("Tanzania", "wheat"): (0.0, 0, 0.0, "negligible", None),
    ("Uganda", "sorghum"): (0.0, 21, 0.9, "negligible", None),
}

GRADE_RANK = {"INVALID as rainfed": 3, "materially biased": 2, "locally biased": 1,
              "negligible": 0, "unknown": 0}

# What a reader must do differently, per grade. Short enough for an app panel.
GUIDANCE = {
    "INVALID as rainfed":
        "IRRIGATED CROP — CPI, yield and stress are NOT crop condition here. The balance credits "
        "rainfall only, so the deficit shown is the irrigation requirement.",
    "materially biased":
        "Partly irrigated: condition is understated in the irrigated units listed. Do not rank "
        "them against rainfed units.",
    "locally biased":
        "Locally irrigated: national aggregates are sound, the units listed are not.",
    "negligible": "",
}


def grade(country, crop):
    """Exposure grade for a (country, crop). 'unknown' if SPAM has no entry."""
    return EXPOSURE.get((_ckey(country), _crop(crop)), (None, None, None, "unknown", None))[3]


def _ckey(c):
    return str(c).replace(" ", "_")


def _crop(c):
    return str(c).lower()


def record(country, crop):
    """Full record as a dict, or None when the pair is not in SPAM."""
    e = EXPOSURE.get((_ckey(country), _crop(crop)))
    if e is None:
        return None
    nat, ha, mx, g, units = e
    return {"national_irr_pct": nat, "irr_area_ha": ha, "admin1_max_pct": mx,
            "grade": g, "compromised_units": units}


def asset_properties(country, crop):
    """Properties to attach to an Earth Engine asset. Always includes the grade, so a reader can
    filter on it without knowing the table."""
    r = record(country, crop)
    if r is None:
        return {"irrigation_exposure": "unknown",
                "irrigation_note": "no SPAM 2020 technology split for this crop"}
    p = {"irrigation_exposure": r["grade"],
         "irrigation_national_pct": r["national_irr_pct"],
         "irrigation_area_ha": r["irr_area_ha"],
         "irrigation_admin1_max_pct": r["admin1_max_pct"],
         "irrigation_source": "SPAM 2020 V2r2 physical area, _I / _A"}
    if r["compromised_units"]:
        p["irrigation_units"] = r["compromised_units"]
    if GUIDANCE.get(r["grade"]):
        p["irrigation_note"] = GUIDANCE[r["grade"]]
    return p


def app_note(country, crop):
    """One clause for an app product note. Empty string when exposure is negligible."""
    r = record(country, crop)
    if r is None or r["grade"] in ("negligible", "unknown"):
        return ""
    bits = [f"IRRIGATION: {r['grade']}",
            f"{r['national_irr_pct']:g} % of {crop} area irrigated nationally"]
    if r["compromised_units"]:
        bits.append("affected: " + r["compromised_units"])
    bits.append(GUIDANCE[r["grade"]])
    return " · ".join(b for b in bits if b)


def summary():
    from collections import Counter
    c = Counter(v[3] for v in EXPOSURE.values())
    return dict(c)


if __name__ == "__main__":
    print(f"{len(EXPOSURE)} (country, crop) pairs\n")
    for (co, cr), v in sorted(EXPOSURE.items(), key=lambda kv: -GRADE_RANK[kv[1][3]]):
        if v[3] == "negligible":
            continue
        print(f"  {co:12s} {cr:8s} {v[3]:20s} nat {v[0]:5.1f} %  {v[1]:>7,} ha  max {v[2]:5.1f} %")
        print(f"               -> {app_note(co, cr)[:150]}")
    print(f"\nnegligible: {sum(1 for v in EXPOSURE.values() if v[3] == 'negligible')} pairs")
